name: gatezero_demo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  confetti: ^0.6.0
  convex_bottom_bar: ^3.0.0
  bubble: ^1.2.1
  font_awesome_flutter: ^9.2.0
  lottie: ^1.2.1
  carousel_slider: ^4.0.0
  like_button: ^2.0.3
  modal_bottom_sheet: ^2.0.0
  fluttertoast: ^8.0.8
  stories_for_flutter: ^1.1.1
  sliding_number: ^0.0.4
  wave: ^0.2.0
  async_button_builder: ^2.1.4
  flutter_colorpicker: ^1.0.2
  matrix_gesture_detector: ^0.1.0
  delayed_display: ^2.0.0
  pull_to_refresh: ^2.0.0
  screenshot: ^1.2.3
  expandable_widgets: ^1.0.2
  polygon_clipper: ^1.0.2
  coupon_uikit: ^0.0.1
  speech_balloon: ^0.0.4
  concentric_transition: ^1.0.1+1
  badges: ^2.0.2
  styled_widget: ^0.4.0+3

  # Services
  provider: ^6.0.1
  url_launcher: ^6.0.12
  youtube_player_flutter: ^8.0.0
  google_maps_flutter: ^2.0.11
  share_plus: ^3.0.4
  path_provider: ^2.0.6
  image_picker: ^0.8.4+4
  qr_code_scanner: ^0.6.1
  permission_handler: ^8.1.6
  adaptive_theme: ^2.3.0
  easy_localization: ^3.0.0
  flutter_native_splash: ^2.1.1
  http: ^0.13.4
  ar_flutter_plugin: ^0.6.2
  auto_route: ^3.2.4
  get_it: ^7.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner:
#  flutter packages pub run build_runner watch

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_v2.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_v2.png"
#  flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  color: "#ffffff"
  image: assets/logoWText.png

  android_12:

  icon_background_color: "#111111"
  android_gravity: center

#  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/bottom_navigation/
    - assets/images/
    - assets/images/challenge/
    - assets/images/challenge/icons/
    - assets/images/challenge/images/
    - assets/icons/
    - assets/icons/faq/
    - assets/icons/leader_board/
    - assets/icons/badges/unlocked/
    - assets/icons/badges/locked/
    - assets/gifs/
    - assets/gifs/landing/
    - assets/gifs/statistics/
    - assets/mocks/
    - assets/mocks/prizes/
    - assets/mocks/profile_pics/
    - assets/mocks/posts/
    - translations/

  fonts:
    - family: 'MontserratAlternates'
      fonts:
        - asset: fonts/Montserrat_Alternates/MontserratAlternates-Regular.ttf
